"""initial schema

Revision ID: 838b36e7ff82
Revises: 
Create Date: 2026-09-16 15:35:04.394284

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '838b36e7ff82'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Istniejąca instalacja miała schemat tworzony przez db.create_all().
    # Dla niej ten revision jest bezpiecznym punktem bazowym; kolejny revision
    # wykona rzeczywistą zmianę schematu.
    if inspect(op.get_bind()).has_table('car'):
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('vin', sa.String(length=32), nullable=True),
    sa.Column('reg_number', sa.String(length=16), nullable=True),
    sa.Column('first_registration', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reg_number'),
    sa.UniqueConstraint('vin')
    )
    op.create_table('mqtt_published_car',
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('car_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('car_owners',
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('car_id', 'user_id')
    )
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_car_id'), ['car_id'], unique=False)

    op.create_table('fuel_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('km', sa.Integer(), nullable=False),
    sa.Column('liters', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_per_l', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('station', sa.String(length=120), nullable=True),
    sa.Column('full_tank', sa.Boolean(), nullable=False),
    sa.Column('unrecorded_refuels_since_last_full', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fuel_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fuel_entry_car_id'), ['car_id'], unique=False)

    op.create_table('insurance_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=False),
    sa.Column('insurer', sa.String(length=128), nullable=True),
    sa.Column('policy_no', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('insurance_policy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_insurance_policy_car_id'), ['car_id'], unique=False)

    op.create_table('odometer_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('km', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('odometer_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_odometer_entry_car_id'), ['car_id'], unique=False)

    op.create_table('service_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('km', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vendor', sa.String(length=120), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_entry_car_id'), ['car_id'], unique=False)

    op.create_table('service_interval',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('interval_km', sa.Integer(), nullable=True),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('last_done_km', sa.Integer(), nullable=True),
    sa.Column('last_done_date', sa.Date(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_interval', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_interval_car_id'), ['car_id'], unique=False)

    op.create_table('tech_inspection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=False),
    sa.Column('result', sa.String(length=32), nullable=True),
    sa.Column('station', sa.String(length=128), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tech_inspection', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tech_inspection_car_id'), ['car_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tech_inspection', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tech_inspection_car_id'))

    op.drop_table('tech_inspection')
    with op.batch_alter_table('service_interval', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_interval_car_id'))

    op.drop_table('service_interval')
    with op.batch_alter_table('service_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_entry_car_id'))

    op.drop_table('service_entry')
    with op.batch_alter_table('odometer_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_odometer_entry_car_id'))

    op.drop_table('odometer_entry')
    with op.batch_alter_table('insurance_policy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insurance_policy_car_id'))

    op.drop_table('insurance_policy')
    with op.batch_alter_table('fuel_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fuel_entry_car_id'))

    op.drop_table('fuel_entry')
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_car_id'))

    op.drop_table('document')
    op.drop_table('car_owners')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('mqtt_published_car')
    op.drop_table('car')
    # ### end Alembic commands ###
